name: test_on_mars
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.1
  connectivity_plus: ^3.0.6
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.3.0
  google_fonts: ^4.0.3
  hydrated_bloc: ^9.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  multiple_result: ^4.0.0
  path_provider: ^2.0.14
  stream_transform: ^2.1.0
  transparent_image: ^2.0.1


dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
